spring:
  config:
    import: .env[.properties]
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_DOMAIN}:5432/postgres?currentSchema=users
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  application:
    name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_DOMAIN}:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
