apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
data:
  MONGODB_DOMAIN: mongodb-service-common
  KAFKA_BOOTSTRAP_SERVERS: my-cluster-kafka-bootstrap.strimzi
  TICKET_SERVICE_DOMAIN: tickets-service
  REDIS_HOST: redis-service