apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful-common
spec:
  serviceName: mongodb-service-common
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-common
  template:
    metadata:
      labels:
        app: mongodb-common
    spec:
      containers:
        - name: common-service-mongodb
          image: mongo:6.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets-common
                  key: MONGODB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets-common
                  key: MONGODB_PASSWORD
      volumes:
        - name: mongo-db
          hostPath:
            path: /data
  volumeClaimTemplates:
    - metadata:
        name: mongo-db
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

