apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: tickets-app
          image: eyakauleva/ticket-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: MONGODB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: tickets-configmap
                  key: MONGODB_DOMAIN
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets-common
                  key: MONGODB_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secrets-common
                  key: MONGODB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: tickets-configmap
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: POSTGRES_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: tickets-configmap
                  key: POSTGRES_DOMAIN
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-common
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets-common
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: tickets-configmap
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASSWORD