name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}
  IMAGE_TAG: 0.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker.io
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

#      - name: Build Docker image
#        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:$IMAGE_TAG
#
#      - name: Push image to Docker.io
#        run: docker push $DOCKER_USER/$REPO_NAME:$IMAGE_TAG

      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
